BelexpLogistikWebApp/Controllers/CarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BelexpLogistikWebApp.Controllers
{
    public class CarController : Controller
    {
        BelexpLogistikContext db;
        public CarController(BelexpLogistikContext context)
        {
            db = context;
        }
        public IActionResult Index()
        {
            var cars = db.Cars.Include(p => p.Owner);
            return View(cars);
        }
    }
}

BelexpLogistikWebApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using BelexpLogistikWebApp.Models;
using Microsoft.AspNetCore.Identity;

namespace BelexpLogistikWebApp.Controllers
{
    public class HomeController : Controller
    {
        UserManager<User> _userManager;
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger, UserManager<User> userManager)
        {
            _userManager = userManager;
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View(_userManager.Users.ToList());
        }
        public IActionResult About()
        {
            return View("About");
        }
        public IActionResult Autopark()
        {
            return View("Autopark");
        }
        
        public IActionResult Service()
        {
            return View("Service");
        }
        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BelexpLogistikWebApp/Controllers/OrderController.cs
using System;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace BelexpLogistikWebApp.Controllers
{
    public class OrderController : Controller
    {
        BelexpLogistikContext db;
        public OrderController(BelexpLogistikContext context)
        {
            db = context;
        }
        public IActionResult Index()
        {
            var orders = db.Orders.Include(p => p.Ride);
            return View(orders);
        }
        public IActionResult Info(int? id)
        {
            var orders = db.Orders.Include(p => p.Ride);
            var order = orders.Where(p => p.Id == id).FirstOrDefault(p => p.Id == id);
            return View(order);
        }
        public IActionResult InfoEnd(int? id)
        {
            var orders = db.Orders.Include(p => p.Ride);
            var order = orders.Where(p => p.Id == id).FirstOrDefault(p => p.Id == id);
            return View(order);
        }
        [HttpGet]
        public ActionResult CreateOrder()
        {
            return View("CreateOrder");
        }
        [HttpPost]
        public ActionResult CreateOrder(Orders order)
        {
            db.Orders.Add(order);
            db.SaveChanges();
            return View("Complete");
        }
        [HttpGet]
        public ActionResult EditOrder(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }
            Orders order = db.Orders.Find(id);
            if (order != null)
            {
                SelectList waybills = new SelectList(db.Waybill, "Id", "WaybillSeries", order.WaybillId);
                ViewBag.WaybillId = waybills;
                return View(order);
            }
            return HttpNotFound();
        }

        private ActionResult HttpNotFound()
        {
            throw new NotImplementedException();
        }

        [HttpPost]
        public ActionResult EditOrder(Orders order)
        {
            db.Entry(order).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

BelexpLogistikWebApp/Controllers/OwnerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BelexpLogistikWebApp.Controllers
{
    public class OwnerController : Controller
    {
        BelexpLogistikContext db;
        public OwnerController(BelexpLogistikContext context)
        {
            db = context;
        }
        public IActionResult Index()
        {
            var owners = db.CarOwner;
            return View(owners);
        }
        [HttpGet]
        [Authorize(Roles = "Логист")]
        public ActionResult Delete(int id)
        {
            CarOwner carOwner = db.CarOwner.Find(id);
            if (carOwner == null)
            {
                return HttpNotFound();
            }
            return View(carOwner);
        }

        private ActionResult HttpNotFound()
        {
            throw new NotImplementedException();
        }

        [HttpPost, ActionName("Delete")]
        [Authorize(Roles = "Логист")]
        public ActionResult DeleteConfirmed(int id)
        {
            CarOwner carOwner = db.CarOwner.Find(id);
            if (carOwner == null)
            {
                return HttpNotFound();
            }
            db.CarOwner.Remove(carOwner);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public IActionResult Edit()
        {
            var owners = db.CarOwner;
            return View(owners);
        }
        [HttpGet]
        [Authorize(Roles = "Логист")]
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [Authorize(Roles = "Администратор")]
        public ActionResult Create(CarOwner carOwner)
        {
            db.CarOwner.Add(carOwner);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

BelexpLogistikWebApp/Controllers/RideController.cs
using System;
using System.Linq;
using BelexpLogistikWebApp.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace BelexpLogistikWebApp.Controllers
{
    public class RideController : Controller
    {
        UserManager<User> _userManager;
        BelexpLogistikContext db;
        public RideController(BelexpLogistikContext context, UserManager<User> userManager)
        {
            db = context;
            _userManager = userManager;
        }
        public IActionResult Index()
        {
            var rides = db.Ride.Include(p => p.Car).Include(p => p.Driver).Include(p => p.Order);
            return View(rides);
        }
        [HttpGet]
        public ActionResult CreateRide()
        {
            SelectList drivers = new SelectList(db.Drivers.Where(p => p.IsFree == true), "Id", "DriverSurname");
            ViewBag.Drivers = drivers;
            SelectList orders = new SelectList(db.Orders.Where(p => p.IsComplete == false), "Id", "Id");
            ViewBag.Orders = orders;
            SelectList cars = new SelectList(db.Cars, "Id", "CarModel");
            ViewBag.Cars = cars;
            return View();
        }
        [HttpPost]
        public ActionResult CreateRide(Ride ride)
        {
            db.Ride.Add(ride);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public IActionResult DriverRides()
        {
            var user = User.Identity.Name;
            var rides = db.Ride.Include(p => p.Car).Include(p => p.Driver).Include(p => p.Order).Where(p => p.Driver.Other == user);
            return View(rides);
        }
        [HttpGet]
        public ActionResult EditStatus(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }
            Ride ride = db.Ride.Find(id);
            if (ride != null)
            {
                return View(ride);
            }
            return HttpNotFound();
        }

        private ActionResult HttpNotFound()
        {
            throw new NotImplementedException();
        }

        [HttpPost]
        public ActionResult EditStatus(Ride ride)
        {
            db.Entry(ride).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("DriverRides");
        }
        public IActionResult Info(int? id)
        {
            var rides = db.Ride.Include(p => p.Order).Include(p => p.Driver).Include(p => p.Car);
            var ride = rides.Where(p => p.Id == id).FirstOrDefault(p => p.Id == id);
            return View(ride);
        }
    }
}

BelexpLogistikWebApp/Views/Home/About.cshtml
@model IEnumerable<BelexpLogistikWebApp.Models.User>
@{
    ViewData["Title"] = "About";
}
<meta charset="utf-8">
<link href='http://fonts.googleapis.com/css?family=Roboto:700' rel='stylesheet' type='text/css'>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
<link href="~/css/adminmainpage.css" rel="stylesheet" type="text/css">

<body>
    <div clss="divImgAboutHistory">
        <img src="https://beleks.ibiz.by/images/company/27279/header.jpg" class="backDivMainIMGAboytGostoty" />
        <span class="spanHistory">ИСТОРИЯ КОМПАНИИ</span>

    </div>
    <h1>История компании</h1>
    <div class="litllefirstinfpabout">
        <b>Группа компаний «Белэкс»</b> берёт своё начало в <b>1995</b> году, основателями которой стали четыре человека, работавших в сфере международных автоперевозок. Одним из учредителей был <b>Коваленко Василий Михайлович</b>, который и по сей день руководит компанией.
    </div>
    <h1 class="h1bluehigh">
        1995
    </h1>
    <div class="litllefirstinfpabout">
        <!--<img class="transperTrackAbout roadpng" src="~/pic/road.png" alt="=road" />-->

        Изначально <b>«Белэкс»</b> создавался преимущественно как фирма, оказывающая
        экспедиционные услуги. Однако, несколько позже было решено усиленно
        развивать парк собственных транспортных средств. И уже в <b>1998</b> году компания приобрела свой первый автомобиль
        отечественного производства <b>МАЗ</b> с полуприцепом. В <b>2004</b> году компания приобрела ещё три тягача <b>Volvo</b> с полуприцепами.
    </div>
    <h1 class="h1bluehigh">
        <img class="transperTrackAbout floatimgcar" src="~/pic/trucks.png" alt="=cars" />2004
    </h1>

    <div class="litllefirstinfpabout">
        В <b>2006</b> году произошла частичная смена учредителей, в результате которой в компанию пришли <b>Коваленко Александр Михайлович</b>, а также <b>Коваленко Сергей Васильевич</b>. С этого момента началось бурное развитие фирмы: в этом же году были приобретены четыре седельных тягача и четыре полуприцепа к ним. В <b>2008</b> году <b>«Белэкс»</b> приобрел два новых тягача <b>Volvo</b> c полуприцепами <b>Koegel</b> в Германии. Покупка совпала с началом мирового финансового кризиса, что стало первой серьёзной проверкой на прочность компании <b>«Белэкс»</b>. Несмотря на это в <b>2009</b> году было решено приобрести ещё три тягача марки Iveco.
    </div>
    <h1 class="h1bluehigh">2008</h1>
    <img class="transperTrackAbout obtecPNG" src="~/pic/car.png" alt="=cars" />

    <div class="litllefirstinfpabout">
        День за днём велась кропотливая работа, направленная на расширение пакета заказов на грузоперевозки, а также на сокращение накладных расходов, что в свою очередь позволяло предлагать клиентам конкурентные цены. Это дало возможность компании рассчитываться по своим обязательствам перед кредиторами и получать финансирование на дальнейшее развитие. В течение <b>2010-2011</b> года <b>«Белэкс»</b> приобретает <b>15</b> тягачей с полуприцепами, в их числе <b>3</b> рефрижератора.

        В <b>2012</b> году было открыто представительство компании в <b>Узбекистане</b>, <b>г. Ташкент</b>. Следом в <b>2013</b> году было открыто представительство в <b>Казахстане</b>, <b>г. Уральск</b> и в <b>Польше</b>, <b>г. Белосток</b>.
    </div>
    <h1 class="h1bluehigh">2017</h1>
    <div class="litllefirstinfpabout">
        В <b>2017</b> году открыто представительство в России <b>г.Новозыбков</b> со своим подвижным составом на российской регистрации.
    </div>
    <h1 class="h1bluehigh">
        <img class="transperTrackAbout" src="~/pic/cars.png" alt="=cars" />
        2019
    </h1>
    <div class="litllefirstinfpabout">
        К 2019 ГОДУ АВТОПАРК КОМПАНИИ НАСЧИТЫВАЕТ<br />
        <span class="spanTextSome"> более 80 АВТОМОБИЛЕЙ И 95 ПОЛУПРИЦЕПОВ</span>
    </div>
    <div class="litllefirstinfpabout">
        На сегодняшний день <b>«Белэкс»</b> — это группа компаний с офисами в пяти странах и автопарком более восьмидесяти автопоездов, с возможностью выполнения перевозок от <b>Португалии</b> до <b>Сахалина</b>, в том числе дорогих, опасных грузов.
    </div>
</body>

BelexpLogistikWebApp/Views/Home/Autopark.cshtml
@model IEnumerable<BelexpLogistikWebApp.Models.User>
@{
    ViewData["Title"] = "Autopark";
}
<meta charset="utf-8">
<link href='http://fonts.googleapis.com/css?family=Roboto:700' rel='stylesheet' type='text/css'>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
<link href="~/css/adminmainpage.css" rel="stylesheet" type="text/css">

<body>
    <div clss="divImgAboutHistory">
        <img src="https://beleks.ibiz.by/images/company/27279/header.jpg" class="backDivMainIMGAboytGostoty" />
        <span class="spanHistory">АВТОПАРК</span>
    </div>
    <h1>Автопарк компании «Белэкс»</h1>
    <div class="litllefirstinfpabout">
        Автопарк Белэкс насчитывает более восьмидесяти автопоездов <b>VOLVO</b>, <b>IVECO</b>, <b>SCANIA</b>, <b>DAF</b>, <b>MAN</b>, <b>KAMAZ</b>, <b>RENO</b> объемом до <b>92м3</b>, соответствующих экологическим нормам <b>Европейского Союза</b>, имеющих возможность перевозки <b>ADR</b>-грузов <b>2,3,4,5,6,8,9</b>-го классов опасности. Компания также выполняет перевозки грузов с высокой стоимостью без таможенного сопровождения. Клиенты доверяют нам самое ценное: страховое покрытие компании по одному страховому случаю составляет <b>1 000 000 EUR</b>. Подвижной состав на белорусской, российской, польской, казахской и узбекской регистрации, что позволяет нам выполнять самые замысловатые перевозки собственным транспортом от Португалии до Сахалина.»
    </div>
    <h1 class="h1bluehigh sizeblueh1">
        Все наши филиалы
        имеют собственный автопарк
    </h1>
    <img class="sizepicAytopark1" src="~/pic/Autopark1.jpg" />
    <h1 class="h1bluehigh sizeblueh1">
        Обновленный подвижной
        состав для лучшей работы
    </h1>
    <img class="sizepicAytopark2" src="~/pic/Autopark2.jpg" />

</body>

BelexpLogistikWebApp/Views/Home/Index.cshtml
@model IEnumerable<BelexpLogistikWebApp.Models.User>
@{
    ViewData["Title"] = "Home Page";
}
<meta charset="utf-8">
<link href='http://fonts.googleapis.com/css?family=Roboto:700' rel='stylesheet' type='text/css'>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
<link href="~/css/adminmainpage.css" rel="stylesheet" type="text/css">
<style>
</style>
@*<body>*@

    @if (User.Identity.IsAuthenticated)
    {
        if (User.IsInRole("Администратор"))
        {
            <div class="widget">
                <h3>Выберите действие</h3>
                <ul>
                    <li class="color"><a asp-controller="Users" asp-action="Index" id="button1">Управление пользователями</a></li>
                    <li class="color"><a asp-controller="Roles" asp-action="Index" id="button2" class="buttonText">Управление ролями</a></li>
                    <li class="color"><a asp-controller="Users" asp-action="DriverList" id="button1">Список водителей</a></li>
                </ul>
            </div>
        }
        if (User.IsInRole("Логист"))
        {
            <div class="widget widget2">
                <h3>Меню</h3>
                <ul>
                   @* <li class="color"><a asp-controller="Driver" asp-action="Drivers" id="button1">Список водителей</a></li>*@
                    <li class="color" id="but2"><a asp-controller="Order" asp-action="Index" id="button2" class="buttonText">Заказы</a></li>
                    <li class="color"><a asp-controller="Ride" asp-action="Index" id="button1">Список поездок</a></li>
                    <li class="color" id="but2"><a asp-controller="Waybill" asp-action="Index" id="button2" class="buttonText">Путевые листы</a></li>
                    <li class="color" id="but2"><a asp-controller="Owner" asp-action="Index" id="button2" class="buttonText">Владельцы машин</a></li>
                    <li class="color" id="but2"><a asp-controller="Car" asp-action="Index" id="button2" class="buttonText">Автопарк</a></li>
                </ul>
            </div>
        }
        if (User.IsInRole("Водитель"))
        {
            <div class="widget widget2">
                <h3>Меню</h3>
                <ul>
                    <li class="color"><a asp-controller="Ride" asp-action="DriverRides" id="button1">Мои поездки</a></li>
                </ul>
            </div>
        }
    }
    else
    {
        //<div class="htmlMainStrDiv">
            <img src="https://beleks.ibiz.by/images/company/27279/header.jpg" class="backDivMainIMG" />
           // <div class="backgrDivMainFoot">
                <span class="belexwhitemain">ГРУППА КОМПАНИЙ<br></span>
                <span class="belexbluemain">БЕЛЭКС<br></span>
                <span class="belexblueminmain">
                    НАДЁЖНОСТЬ И ПРОФЕССИОНАЛИЗМ В ДЕЙСТВИИ<br />
                    ДОВЕРЯЯ НАМ - ВЫ ДЕЛАЕТЕ РАЗУМНЫЙ ВЫБОР
                </span>
         //   </div>
       // </div>
    }
@*</body>*@

BelexpLogistikWebApp/Views/Home/Service.cshtml
@model IEnumerable<BelexpLogistikWebApp.Models.User>
@{
    ViewData["Title"] = "Service";
}
<meta charset="utf-8">
<link href='http://fonts.googleapis.com/css?family=Roboto:700' rel='stylesheet' type='text/css'>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
<link href="~/css/adminmainpage.css" rel="stylesheet" type="text/css">

<div class="containerServiceInformation">
    <div clss="divImgAboutHistory">
        <img src="https://beleks.ibiz.by/images/company/27279/header.jpg" class="backDivMainIMGAboytGostoty" />
        <span class="spanHistory">УСЛУГИ</span>
    </div>
    <div class="NavigationServis">
        <ul class="UlAutoperev">
            <li>
                <a href="#autoperevoz">
                    АВТОМОБИЛЬНЫЕ ПЕРЕВОЗКИ
                </a>
            </li>
            <li>
                <a href="#ferperevoz">
                    ЖЕЛЕЗНОДОРОЖНЫЕ ПЕРЕВОЗКИ
                </a>
            </li>
            <li>
                <a href="#seaperevoz">
                    МОРСКИЕ ПЕРЕВОЗКИ
                </a>
            </li>
            <li>
                <a href="#aviaperevoz">
                   АВИАПЕРЕВОЗКИ
                </a>
            </li>
        </ul>
    </div>
    <div class="infoService">
        <p>
            Наша компания была образована в 1995 году как фирма, занимающаяся преимущественно экспедированием грузов. За это время в компании сформировался коллектив, знающий свою работу и умеющий качественно ее выполнять. В процессе трудовой деятельности мы заработали положительную репутацию в плане надежности и качества наших услуг.
        </p>
        <h1 class="autoperevH1"><a name="autoperevoz"></a>Автомобильные перевозки</h1>
        <img src="~/pic/autotrackserv.png" class="autoservPng" />
        <p >
            Автомобильными перевозками удобно пользоваться при необходимости доставить груз на небольшое расстояние. Гибкая система планирования маршрута позволяет быстро перевозить товары, а развитая инфраструктура дает возможность транспортировать грузы, в том числе и негабаритные, «от двери до двери». Специалисты нашей компании готовы полностью проконтролировать процесс доставки, а также провести консультации по любым возникающим вопросам.
        </p>
        <h1 class="autoperevH2"><a name="ferperevoz">Железнодорожные перевозки</a></h1>
        <img src="~/pic/trani.png" class="poezdpng" />
        <p>
            Железнодорожные перевозки являются наиболее востребованным способом перевозки грузов по России, с ее дальними расстояниями и непредсказуемыми погодными условиями. Кроме того, железнодорожная транспортировка груза выгодно отличается от других способов доставки своей невысокой стоимостью.
        </p>
        <h1 class="autoperevH1"><a name="seaperevoz">Морские перевозки</a></h1>
        <img src="~/pic/ddd.png" class="sudnopngserv" />
        <p>
            Морские перевозки — самый экономичный способ международной доставки груза.С помощью морского транспорта перевозятся любые грузы, включая генеральные. Благодаря сочетанию низкой стоимости, удобного документооборота и высокого уровня безопасности этот способ доставки является одним из самых экономичных и востребованных. Для удобства морских перевозок даже была изобретена специальная грузовая единица — контейнер.
        </p>
        <img src="~/pic/sam.png" class="aviaTransPNG"/>
        <h1 class="autoperevH2"><a name="aviaperevoz">Авиоперевозки</a></h1>
        <p>
            Авиаперевозки являются наиболее удобным способом доставки грузов небольшого объема. Воздушный транспорт — это самый быстрый, а иногда и единственно возможный, вариант транспортировки грузов в любую точку мира, что особенно актуально для ценных или скоропортящихся товаров.

            При всех очевидных преимуществах в скорости, надежности и безопасности, авиаперевозки сегодня стоят недешево. Однако профессионалы сделают все возможное, чтобы стоимость этой услуги стала приемлемой.s
        </p>
    </div>
</div>